package com.swm.ventybackend.content;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "content")
@Getter
@Setter
public class Content {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String contentId;

    @DynamoDBAttribute
    private String fileName;

    @DynamoDBAttribute
    private String fileUrl;

    @DynamoDBAttribute
    private String createdDate;

    @DynamoDBAttribute
    private String like;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String fileType;

}
